// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef WC_ImageBox_h
#define WC_ImageBox_h
#include <FL/Fl.H>
#undef WC_ImageBox_h
namespace EE698K { namespace GUI { class WC_ImageBox; }}; 
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>

class EE698K::GUI::WC_ImageBox : public Fl_Group {
public:
  WC_ImageBox(int X, int Y, int W, int H, const char *L = 0);
protected:
  Fl_Box *wBox;
public:
  virtual void resize(int X, int Y, int W, int H);
};
#endif
