// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef WC_MainWindow_h
#define WC_MainWindow_h
#include <FL/Fl.H>
#undef WC_MainWindow_h
#include "UI_ImageBox.h"
#include "UI_DrawImageBox.h"
namespace EE604A {namespace GUI {class WC_MainWindow;}}; 
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>

class EE604A::GUI::WC_MainWindow : public Fl_Double_Window {
  void _WC_MainWindow();
public:
  WC_MainWindow(int X, int Y, int W, int H, const char *L = 0);
  WC_MainWindow(int W, int H, const char *L = 0);
  WC_MainWindow();
  static Fl_Menu_Item menu_[];
private:
  inline void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
  inline void cb_Load_i(Fl_Menu_*, void*);
  static void cb_Load(Fl_Menu_*, void*);
  inline void cb_Save_i(Fl_Menu_*, void*);
  static void cb_Save(Fl_Menu_*, void*);
  inline void cb_Quit_i(Fl_Menu_*, void*);
  static void cb_Quit(Fl_Menu_*, void*);
  inline void cb_Inpaint_i(Fl_Menu_*, void*);
  static void cb_Inpaint(Fl_Menu_*, void*);
  inline void cb_small_i(Fl_Menu_*, void*);
  static void cb_small(Fl_Menu_*, void*);
  inline void cb_medium_i(Fl_Menu_*, void*);
  static void cb_medium(Fl_Menu_*, void*);
public:
  UI_DrawImageBox *wImageBox1;
  UI_ImageBox *wImageBox2;
private:
  virtual void WOpen_cb (void) {}; 
  virtual void WQuit_cb (void) {}; 
  virtual void WInpaint_cb (void) {}; 
  virtual void WBlur_cb (void) {}; 
  virtual void WSmall_cb (void) {}; 
  virtual void WMedium_cb (void) {}; 
  virtual void WLoadPoints_cb (void) {}; 
  virtual void WSavePoints_cb (void) {}; 
};
#endif
