// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "../include/WC_ImageBox.h"
EE604A::GUI::WC_ImageBox::WC_ImageBox(int X, int Y, int W, int H, const char *L)
  : Fl_Group(0, 0, W, H, L) {
{ wBox = new Fl_Box(0, 0, 100, 100);
  wBox->box(FL_GTK_THIN_UP_BOX);
  Fl_Group::current()->resizable(wBox);
} // Fl_Box* wBox
position(X, Y);
end();
}

void EE604A::GUI::WC_ImageBox::resize(int X, int Y, int W, int H) {
  wBox->resize (0, 0, W - 20, H - 20);
  Fl_Group::resize (X, Y, W, H);
}
